import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import HomePage from '../pages/HomePage';
import fetchMock from 'jest-fetch-mock';

// This file was pre generated by GPT and adjusted by Wellington Rutes

const mockNavigate = jest.fn();
jest.mock('react-router-dom', () => ({
    ...jest.requireActual('react-router-dom'),
    useNavigate: () => mockNavigate,
}));

global.fetch = jest.fn(() =>
    Promise.resolve({
      json: JSON.stringify({ fibonacci_sequence: [0, 1, 1, 2, 3] })
    }),
  ) as jest.Mock;

describe('HomePage Component', () => {

    it('renders Navbar, Footer, and form elements correctly', () => {
        render(<HomePage />);

        expect(screen.getByText(/Fibonacci Sequence Generator/i)).toBeInTheDocument();
        expect(screen.getByLabelText(/Enter a Number/i)).toBeInTheDocument();
        expect(screen.getByRole('button', { name: /Generate Fibonacci Sequence/i })).toBeInTheDocument();
        expect(screen.getByText(/© BioHub - Fibonacci App/i)).toBeInTheDocument();
    });

    it('updates input value correctly', () => {
        render(<HomePage />);

        const inputElement = screen.getByLabelText(/Enter a Number/i) as HTMLInputElement;
        fireEvent.change(inputElement, { target: { value: '5' } });
        
        expect(inputElement.value).toBe('5');
    });

    it('calls fetch and navigates to result page on valid submission', async () => {
        global.fetch = jest.fn(() =>
            Promise.resolve({
              json: () => Promise.resolve({ fibonacci_sequence: '0, 1, 1, 2, 3' }),
            }),
          ) as jest.Mock;

        render(<HomePage />);

        const inputElement = screen.getByLabelText(/Enter a Number/i) as HTMLInputElement;
        const submitButton = screen.getByRole('button', { name: /Generate Fibonacci Sequence/i });

        fireEvent.change(inputElement, { target: { value: '5' } });
        fireEvent.click(submitButton);

        await waitFor(() => {
            expect(fetch).toHaveBeenCalledWith('http://localhost:8000/api/v1/generate/', expect.any(Object));
            expect(mockNavigate).toHaveBeenCalledWith('/result', { state: { fibonacciNumbers: '0, 1, 1, 2, 3' } });
        });
    });

    it('does not call fetch or navigate on empty input', async () => {
        render(<HomePage />);

        const submitButton = screen.getByRole('button', { name: /Generate Fibonacci Sequence/i });
        fireEvent.click(submitButton);

        expect(fetchMock).not.toHaveBeenCalled();
        expect(mockNavigate).not.toHaveBeenCalled();
    });
});
