import React from 'react';
import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

// This code was 100% generated by GPT
const Navbar = () => {
    return (
        <AppBar position="static">
            <Toolbar>
                <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                    Fibonacci Sequence Generator
                </Typography>
            </Toolbar>
        </AppBar>
    );
};

export default Navbar;
