import React from 'react';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';

// This code was 100% generated by GPT
const Footer = () => {
    return (
        <Box sx={{ bgcolor: 'primary.main', p: 2, mt: 'auto', textAlign: 'center' }}>
            <Typography variant="body1" color="white">
                © BioHub - Fibonacci App
            </Typography>
        </Box>
    );
};

export default Footer;
